// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;

[Flags()]
public enum BuildingType {
  Foundation = 1,
  Pillar = 2,
  Wall = 4,
  Ceiling = 8,
  Stairs = 16,
  Props = 32,
  Door = 64,
  WallProps = 128,
  Roof = 256,
  RoofTries = 512,
}
